### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by MarcoNicolodi** [mkg0/jest-webpack-resolver#12]
Hi. 

Thank you for this library. It has solved a CI issue of ours. 

But it might have room for improvements. Our tests are 10 times slower with the webpack resolver. 

![image](https://user-images.githubusercontent.com/8574010/36857648-d106d7c4-1d57-11e8-87a9-27ced87678ab.png)
with resolver/without resolver

Do you have any performance advices for us?

**Comment by evanc** [comment]
I noticed the same thing and found that a little caching fixed the issue for me.

I've made a PR: #13

**Comment by MarcoNicolodi** [comment]
Thanks. Cant wait to be merged :100:

**Comment by mkg0** [comment]
@MarcoNicolodi I released a new version and tested in a small project. Can you check again please?
You can use `--no-cache` option. Also you can give a try @evanc's pr if you replace `^0.2.0` with `evanc/jest-webpack-resolver`.

### with several test suites
Before:
```sh
Test Suites: 5 passed, 5 total
Tests:       11 passed, 11 total
Snapshots:   0 total
Time:        44.198s
Ran all test suites.
✨  Done in 45.49s.
```

After:
With jest's resolver: `16.41s.`
with jest-webpack-resolver: `20.52s.`

### with single test suite
Before:
```
Test Suites: 1 passed, 1 total
Tests:       5 passed, 5 total
Snapshots:   0 total
Time:        11.125s
```
After:
With jest's resolver: `1.208s,`
with jest-webpack-resolver: `3.884s`

**Comment by evanc** [comment]
I tested with my project, which has few tests but a fairly large codebase:

0.2.0: `19.473s`
My PR: `5.969s`
0.3.0: `5.603s`

This looks pretty good to me. Thanks!

**Comment by MarcoNicolodi** [comment]
In a codebase with 400 tests:

No resolver: `16.021s`
0.2.0: `159.178s`
0.3.0 --no-cache: `22.449s`
evanc PR: `18.803s`

Downgrading from 16s to 22s seems good enough for us. 

Thank you guys.
