### ISSUE TITLE
Support jest.config.js as for config.

### ISSUE THREAD

**Issue by DzoQiEuoi** [mkg0/jest-webpack-resolver#2]
It would be nice if I configure this module in my jest config file instead of packages.json.

**Comment by mkg0** [comment]
jest configuration doesn't allow custom config properties like 'jestWebpackResolver' and shows warning. But it can be good especially about testing for package's itself.

**Comment by DzoQiEuoi** [comment]
I'm trying to use this at the moment, but it throws an error on line 11 of index.js because it expect the file to be called jest.config.js whereas mine is jest.config.json.
