### ISSUE TITLE
Add silent option

### ISSUE THREAD

**Issue by guilhermelimak** [mkg0/jest-webpack-resolver#8]
First of all, thanks a lot for this plugin, it's very simple and exactly what I was looking for.

The only think that bugs me a bit is the `Webpack Resolver using: ./config/webpack.client.js` message logged to the console when running tests.

Would you merge a PR that added an option to make this plugin silent or is there such option already (I couldn't find it in the docs)? 
I think I could implement it in a day or two, looks like something simple to do.

Thanks again for creating this :]

**Comment by mkg0** [comment]
It makes sense, thanks for great feedback 👍 

sure PR welcome :)

**Comment by guilhermelimak** [comment]
Sorry for the delay, missed the notification and forgot completely about this thread.

So here's the PR, if something needs to be changed just leave me a comment and tomorrow I can fix it.

cheers

**Comment by mkg0** [comment]
https://github.com/mkg0/jest-webpack-resolver/pull/9
